language: python
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
matrix:
    include:
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.5
          env: TOXENV=docs
        - python: 3.7
          env: TOXENV=lint
          dist: xenial
          sudo: true
        - python: 3.7
          env: TOXENV=py37-cover,coverage
          dist: xenial
          sudo: true
        - python: 3.8-dev
          env: TOXENV=py38
          dist: xenial
          sudo: true
    allow_failures:
        - env: TOXENV=py38

install:
    - travis_retry pip install tox

script:
    - travis_retry tox
