class PlasterError(Exception):
    """
    A base exception for any error generated by plaster.
    """


class NoSectionError(PlasterError, ValueError):
    """
    Raised by a :class:`plaster.ILoader` which cannot find a section.

    :ivar section: The name of the section that does not exist.

    """
    def __init__(self, section, message=None):
        if message is None:
            message = 'Could not find requested section "{0}".'.format(section)
        super(NoSectionError, self).__init__(message)
        self.message = message
        self.section = section


class InvalidURI(PlasterError, ValueError):
    """
    Raised by :func:`plaster.parse_uri` when failing to parse a ``config_uri``.

    :ivar uri: The user-supplied ``config_uri`` string.

    """
    def __init__(self, uri, message=None):
        if message is None:
            message = 'Unable to parse config_uri "{0}".'.format(uri)
        super(InvalidURI, self).__init__(message)
        self.message = message
        self.uri = uri


class LoaderNotFound(PlasterError, ValueError):
    """
    Raised by :func:`plaster.get_loader` when no loaders match the requested
    ``scheme``.

    :ivar scheme: The scheme being matched.
    :ivar protocol: The requested :term:`loader protocol` or ``None``.

    """
    def __init__(self, scheme, protocol=None, message=None):
        if message is None:
            scheme_msg = 'scheme "{0}"'.format(scheme)
            if protocol is not None:
                scheme_msg += ', protocol "{0}"'.format(protocol)
            message = (
                'Could not find a matching loader for the {0}.'
                .format(scheme_msg))
        super(LoaderNotFound, self).__init__(message)
        self.message = message
        self.scheme = scheme
        self.protocol = protocol


class MultipleLoadersFound(PlasterError, ValueError):
    """
    Raised by :func:`plaster.get_loader` when more than one loader matches the
    requested ``scheme``.

    :ivar scheme: The scheme being matched.
    :ivar protocol: The requested :term:`loader protocol` or ``None``.
    :ivar loaders: A list of :class:`plaster.ILoaderInfo` objects.

    """
    def __init__(self, scheme, loaders, protocol=None, message=None):
        if message is None:
            scheme_msg = 'scheme "{0}"'.format(scheme)
            if protocol is not None:
                scheme_msg += ', protocol "{0}"'.format(protocol)
            loader_list = ', '.join(loader.scheme for loader in sorted(
                loaders, key=lambda v: v.scheme))
            message = (
                'Multiple plaster loaders were found for {0}. '
                'Please specify a more specific config_uri. '
                'Matched loaders: {1}'
            ).format(scheme_msg, loader_list)
        super(MultipleLoadersFound, self).__init__(message)
        self.message = message
        self.scheme = scheme
        self.protocol = protocol
        self.loaders = loaders
